# -*- coding: utf-8 -*-
"""etl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HTshMWG4baSKPFXgnBtqdkCXg6G2MI6I
"""

import pandas as pd
import transform  # Import transformation functions

# EXTRACT
def extract(file_path):
    """Extracts data from a CSV file into a Pandas DataFrame."""
    df = pd.read_csv(file_path)
    return df

# TRANSFORM
def transform_data(df):
    """Applies transformation functions from transform.py to clean and structure the dataset."""
    df = transform.clean_column_names(df)  # Clean column names
    df = transform.drop_duplicated_column(df)  # Drop duplicated column
    df = transform.clean_float_columns(df)  # Clean float columns
    df = transform.handle_missing_values(df)  # Handle missing values
    df = transform.clean_open_ended_columns(df)  # Clean text columns
    df = transform.remove_outliers(df)  # Remove outliers
    df = transform.standardize_float_columns(df)  # Standardize text columns
    df = transform.standardized_cuisine(df)  # Convert to datetime

    return df

# LOAD
def load(df, output_file):
    """Loads the cleaned DataFrame into a CSV file."""
    df.to_csv(output_file, index=False)

# EXECUTION OF ETL PIPELINE
def main():
    """Main ETL pipeline execution."""
    input_file = "food_coded.csv"
    output_file = "processed_food_coded.csv"

    print("Extracting data...")
    df = extract(input_file)    # Load raw data

    print("Transforming data...")
    df = transform_data(df) # Apply transformation functions

    print("Loading data...")
    load(df, output_file)   # Save transformed data

    print("ETL process completed successfully!")

if __name__ == "__main__":
    main()